spring:
  datasource:
    url: jdbc:h2:mem:sample_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job:
      enabled: false

server:
  servlet:
    context-path: "/job"

feign:
  client:
    url: http://localhost:5000
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic